# Generated by Django 4.2.2 on 2023-07-24 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_id', models.IntegerField()),
                ('crsid', models.IntegerField()),
                ('ssnid', models.IntegerField()),
                ('enrol_id', models.CharField(max_length=100, unique=True)),
                ('stu_name', models.CharField(max_length=200)),
                ('doj', models.CharField(max_length=200)),
                ('contact_no', models.BigIntegerField()),
                ('admsn_yr1', models.IntegerField(blank=True, null=True)),
                ('admsn_yr2', models.IntegerField(blank=True, null=True)),
                ('admsn_yr3', models.IntegerField(blank=True, null=True)),
                ('admsn_yr4', models.IntegerField(blank=True, null=True)),
                ('admsn_yr5', models.IntegerField(blank=True, null=True)),
                ('admsn_yr6', models.IntegerField(blank=True, null=True)),
                ('security_fee', models.IntegerField(blank=True, null=True)),
                ('other_fee', models.IntegerField(blank=True, null=True)),
                ('yr1_fee', models.IntegerField(blank=True, null=True)),
                ('yr2_fee', models.IntegerField(blank=True, null=True)),
                ('yr3_fee', models.IntegerField(blank=True, null=True)),
                ('yr4_fee', models.IntegerField(blank=True, null=True)),
                ('yr5_fee', models.IntegerField(blank=True, null=True)),
                ('yr6_fee', models.IntegerField(blank=True, null=True)),
                ('ref_by', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('new_admission', 'New Admission'), ('promoted', 'Promoted'), ('not_promoted', 'Not Promoted'), ('passed', 'Passed'), ('suspended', 'Suspended')], default='not_passed', max_length=20)),
                ('_duration', models.IntegerField(blank=True, editable=False, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alpine_students.admission')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('permanent_address', models.TextField()),
                ('correspondence_address', models.TextField(null=True)),
                ('state', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('parent_phone', models.CharField(max_length=20, null=True)),
                ('guardian_phone', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('exam_passed', models.CharField(max_length=100)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('university_board', models.CharField(max_length=100)),
                ('marks_percentage', models.CharField(max_length=100)),
                ('card_1', models.CharField(max_length=50, null=True)),
                ('card_2', models.CharField(max_length=50, null=True)),
                ('card_3', models.CharField(max_length=50, null=True)),
                ('card_4', models.CharField(max_length=50, null=True)),
                ('eno_1', models.CharField(max_length=50, null=True)),
                ('eno_2', models.CharField(max_length=50, null=True)),
                ('eno_3', models.CharField(max_length=50, null=True)),
                ('eno_4', models.CharField(max_length=50, null=True)),
                ('eno_5', models.CharField(max_length=50, null=True)),
                ('eno_6', models.CharField(max_length=50, null=True)),
                ('eno_7', models.CharField(max_length=50, null=True)),
                ('eno_8', models.CharField(max_length=50, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alpine_students.admission')),
            ],
        ),
    ]
