# Generated by Django 4.2.2 on 2023-06-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='contact_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
