# Generated by Django 4.2.2 on 2023-06-26 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_students', '0003_alter_admission_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('permanent_address', models.TextField()),
                ('correspondence_address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('parent_phone', models.CharField(max_length=20)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('exam_passed', models.CharField(max_length=100)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('university_board', models.CharField(max_length=100)),
                ('marks_percentage', models.CharField(max_length=100)),
                ('card_no_1', models.CharField(max_length=50)),
                ('card_no_2', models.CharField(max_length=50)),
                ('card_no_3', models.CharField(max_length=50)),
                ('card_no_4', models.CharField(max_length=50)),
                ('e_no_1', models.CharField(max_length=50)),
                ('e_no_2', models.CharField(max_length=50)),
                ('e_no_3', models.CharField(max_length=50)),
                ('e_no_4', models.CharField(max_length=50)),
                ('e_no_5', models.CharField(max_length=50)),
                ('e_no_6', models.CharField(max_length=50)),
                ('e_no_7', models.CharField(max_length=50)),
                ('e_no_8', models.CharField(max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alpine_students.admission')),
            ],
        ),
    ]
