# Generated by Django 4.2.2 on 2023-06-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_students', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='card_no_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_no_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_no_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_no_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='e_no_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='e_no_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='e_no_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='e_no_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='e_no_5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='e_no_6',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='e_no_7',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='e_no_8',
        ),
        migrations.AddField(
            model_name='profile',
            name='card_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='eno_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='eno_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='eno_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='eno_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='eno_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='eno_6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='eno_7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='eno_8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='correspondence_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guardian_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parent_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
