# Generated by Django 4.2.2 on 2023-06-29 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_students', '0005_remove_profile_card_no_1_remove_profile_card_no_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('is_promoted', models.BooleanField(default=False)),
                ('is_demoted', models.BooleanField(default=False)),
                ('is_not_passed', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_course_completed', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alpine_students.admission')),
            ],
        ),
    ]
