# Generated by Django 4.2.2 on 2023-06-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_students', '0006_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='year',
            new_name='curr_year',
        ),
    ]
