# Generated by Django 4.2.2 on 2023-06-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_students', '0007_rename_year_promotion_curr_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='is_course_completed',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='is_demoted',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='is_not_passed',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='is_promoted',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='is_suspended',
        ),
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('promoted', 'Promoted'), ('demoted', 'Demoted'), ('not_passed', 'Not Passed'), ('suspended', 'Suspended')], default='not_passed', max_length=20),
        ),
    ]
