# Generated by Django 4.2.2 on 2023-06-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_students', '0008_remove_promotion_is_course_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('promoted', 'Promoted'), ('not_passed', 'Not Passed'), ('suspended', 'Suspended')], default='not_passed', max_length=20),
        ),
    ]
