# Generated by Django 4.2.2 on 2023-06-29 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_students', '0010_promotion_duration_alter_promotion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='duration',
        ),
    ]
