# Generated by Django 4.2.2 on 2023-06-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_students', '0011_remove_promotion_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='_duration',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
