# Generated by Django 4.2.2 on 2023-06-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_students', '0012_promotion__duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='admsn_fee',
            new_name='admsn_yr1',
        ),
        migrations.AddField(
            model_name='admission',
            name='admsn_yr2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='admsn_yr3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='admsn_yr4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='admsn_yr5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='admsn_yr6',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
