# Generated by Django 4.2.2 on 2023-07-24 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alpine_students', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTable',
            fields=[
                ('fee_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('college_id', models.BigIntegerField()),
                ('ssnid', models.BigIntegerField()),
                ('crsid', models.BigIntegerField()),
                ('security', models.BigIntegerField()),
                ('other', models.BigIntegerField()),
                ('admsn_yr1', models.BigIntegerField(null=True)),
                ('admsn_yr2', models.BigIntegerField(null=True)),
                ('admsn_yr3', models.BigIntegerField(null=True)),
                ('admsn_yr4', models.BigIntegerField(null=True)),
                ('admsn_yr5', models.BigIntegerField(null=True)),
                ('admsn_yr6', models.BigIntegerField(null=True)),
                ('yr1', models.BigIntegerField(null=True)),
                ('yr2', models.BigIntegerField(null=True)),
                ('yr3', models.BigIntegerField(null=True)),
                ('yr4', models.BigIntegerField(null=True)),
                ('yr5', models.BigIntegerField(null=True)),
                ('yr6', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeReceipts',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('enrol_id', models.CharField(max_length=100)),
                ('stu_name', models.CharField(max_length=100)),
                ('reg_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sec_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tut_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('other_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pre_bal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rebate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('year', models.IntegerField()),
                ('fee_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpine_students.admission')),
            ],
        ),
        migrations.CreateModel(
            name='FeeBalance',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('reg_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sec_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tut_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('other_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pre_bal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rebate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('curr_year', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpine_students.admission')),
            ],
        ),
    ]
