# Generated by Django 4.2.2 on 2023-06-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereceipts',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
